import './globals.css';
import React, { PropsWithChildren } from 'react';
import { Inter } from 'next/font/google';

import { Header } from '@/components/header';
import { Footer } from '@/components/footer';

import { type Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const GlobalLayout = ({ children }: PropsWithChildren) => {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="flex min-h-screen flex-col bg-white dark:bg-gray-800">
					<Header />
					{children}
					<Footer />
				</div>
			</body>
		</html>
	);
};

export default GlobalLayout;
